### ISSUE TITLE
Equality Explorer: Basics - master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer-basics#1]
_NOTE: This sim is the first screen of equality-explorer.  Checklist items marked as "N/A" (not applicable) will be handled as part of the equality-explorer checklist._

## Design
- [x] **Sim folder and design doc created** (N/A)
  - [x] Create sim folder (N/A)
  - [x] Place design doc in the sim folder (N/A)
- [x] **Sim suggestions doc reviewed** (N/A)
- [x] **Learning goals and standards identified** (N/A)
- [x] **Design concept complete**  (N/A)
- [x] **Wireframes complete** (N/A)
- [x] **Mockups complete** (N/A)
  - [x] Mockups checked for colorblind and greyscale (N/A)
- [x] **Features for PhET-iO discussion** (N/A)
- [x] **Interviews complete** (N/A)
- [x] **Lead designer "sign off"** (N/A)
- [ ] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [x] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 4/17/18)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: N/A)
- [x] **Sim is "feature complete"** (Date: 4/17/18)
- [x] **Code review completed** (N/A)
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped) - see https://github.com/phetsims/equality-explorer/issues/125
  - [x] Verify credits - see phetsims/equality-explorer#2
- [x] **Published** (Date: 7/18/18) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 6/18/18) 
- [x] **Dev testing completed** (Date: 7/5/18) 
- [x] **First RC published** (Date: 7/13/18)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 7/17/18)

**Comment by pixelzoom** [comment]
All remaining checklist items are for @amanda-phet to complete.

**Comment by pixelzoom** [comment]
Lots of checklist items remain here, and this sim has been published for awhile.  @amanda-phet @ariel-phet can you please review?

**Comment by pixelzoom** [comment]
@ariel-phet @amanda-phet Should remaining checklist items be split out into their own issues?

**Comment by ariel-phet** [comment]
https://github.com/phetsims/equality-explorer-basics/issues/7 created for LoL items

**Comment by ariel-phet** [comment]
Relevant issues created for remaining items. Closing
